#!/usr/bin/php
<?php declare(strict_types=1);

use PhpFramework\Application;
use PhpFramework\Console\ArgsInputs;

if (PHP_SAPI !== 'cli') {
    fwrite(STDERR, "This script must be run from the command line.\n");
    exit(1);
}

require_once __DIR__ . '/vendor/autoload.php';

Application::instance()
    ->setBasePath(__DIR__)
    ->handleCommand(new ArgsInputs);
